name: my-xmonad
version: 0.1.0.3
synopsis: My XMonad config
author: Eric Bailey
maintainer: eric@ericb.me
github: yurrriq/dotfiles
license: Unlicense

dependencies:
  - base
  - containers
  - xmonad
  - xmonad-contrib

ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-patterns
  - -Wincomplete-uni-patterns

executable:
  main: xmonad.hs
  ghc-options:
    - -O0
    - -threaded
