#+TITLE: Useful Scripts
#+AUTHOR: Eric Bailey
#+EMAIL: e.bailey@sportradar.com
#+DATE: <2018-08-14 Tue>
#+PROPERTY: :header-args :padline yes

* Fix Sourcetree preferences
  :PROPERTIES:
  :header-args: :tangle bin/fix-stree-prefs :shebang "#! /usr/bin/env sh"
  :END:

Be safer.
#+BEGIN_SRC sh
set -euo pipefail
#+END_SRC

Define a helper function to DRY things up a bit.
#+BEGIN_SRC sh
defaults_write ()
{
    printf "%s : %s => %s\\n" \
           "$1" \
           "$(defaults read com.torusknot.SourceTreeNotMAS "$1")" \
           "$2"

    defaults write com.torusknot.SourceTreeNotMAS "$1" "$2"
}
#+END_SRC

Use Nix's =git=.
#+BEGIN_SRC sh
defaults_write gitCustomPath       /run/current-system/sw/bin/git
defaults_write gitWhichOne         1
#+END_SRC

Use Nix's =git-flow=.
#+BEGIN_SRC sh
defaults_write gitFlowCustomPath   /run/current-system/sw/bin/git-flow
defaults_write gitFlowWhichOne     1
#+END_SRC

Use the correct [[../../git/srus/.gitignore][global .gitignore]].
#+BEGIN_SRC sh
defaults_write gitGlobalIgnoreFile ~/.gitignore
#+END_SRC

Use Nix's =git-lfs=.
#+BEGIN_SRC sh
defaults_write gitLfsCustomPath    /run/current-system/sw/bin/git-lfs
defaults_write gitLfsWhichOne      1
#+END_SRC

Use Nix's =gpg=.
#+BEGIN_SRC sh
defaults_write gpgProgram          /run/current-system/sw/bin
#+END_SRC

* List =git-crypt= GPG users
  :PROPERTIES:
  :header-args: :padline no :tangle bin/git-crypt-users :shebang "#! /usr/bin/env nix-shell"
  :END:

Load the necessary packages, =bash=, =findutils= (for GNU find), and =gnupg=.
#+BEGIN_SRC bash
#! nix-shell --pure -i bash -p bash findutils gnupg
#+END_SRC

Be safer.
#+BEGIN_SRC bash :padline yes
set -euo pipefail
#+END_SRC

Quit if there's no =.git-crypt= directory.
#+BEGIN_SRC bash :padline yes
if [ ! -d .git-crypt ]
then
    echo "No .git-crypt/ found."
    exit 100
fi
#+END_SRC

Find all the GPG-encrypted keys and print just the filename.
#+BEGIN_SRC bash :padline yes
find .git-crypt/keys/default/0/ -type f -name '*.gpg' -printf '%f\n' | \
#+END_SRC

Strip the =.gpg= extension to list only key IDs.
#+BEGIN_SRC bash
    sed 's/.gpg$//' | \
#+END_SRC

Lookup the matching public keys.
#+BEGIN_SRC bash
    xargs gpg --list-public-keys | \
#+END_SRC

# Print only the associated Sportradar email addresses.
#+BEGIN_SRC bash :exports none :tangle no
    awk '/sportradar.com/{ print $NF }' | \
#+END_SRC

Print only email addresses.
#+BEGIN_SRC bash
    awk '/^uid/{ print $NF }' | \
#+END_SRC

Sort the email list.
#+BEGIN_SRC bash
    sort
#+END_SRC

* Attach to a =tmux= session on the k8s bastion
  :PROPERTIES:
  :header-args: :tangle bin/attach :shebang "#! /usr/bin/env bash"
  :END:

This script is based on the one in Luke Sandell's blog post, [[https://luketopia.net/2013/11/02/seamless-ssh-with-tmux-and-kitty/][Seamless SSH with tmux and KiTTY]].

Be safer.
#+BEGIN_SRC bash
set -eux
#+END_SRC

Use the current terminal as the session name, if unspecified.
#+BEGIN_SRC bash
if [ -z "${1:-}" ]; then
    SESSION="$(tty)"
else
    SESSION="$1"
fi
#+END_SRC

Use [[http://tldp.org/LDP/abs/html/refcards.html#AEN22828][parameter expansion]] to strip a prefix ~/dev/~ from =SESSION=.
#+BEGIN_SRC bash
SESSION="${SESSION#/dev/}"
#+END_SRC

Set =TERM= to ~xterm~ to avoid the following error when using [[https://sw.kovidgoyal.net/kitty/][KiTTY]].
#+BEGIN_SRC bash
TERM=xterm
#+END_SRC

#+BEGIN_QUOTE
open terminal failed: missing or unsuitable terminal: xterm-kitty
#+END_QUOTE

Replace the current shell with a remote =tmux= session.
#+BEGIN_SRC bash :exports none
# shellcheck disable=SC2029
#+END_SRC
#+BEGIN_SRC bash :padline no
if ssh bastion tmux has -t "$SESSION"; then
    exec ssh bastion -t "tmux attach -t $SESSION"
else
    exec ssh bastion -t "tmux new -s $SESSION"
fi
#+END_SRC

# Local Variables:
# org-src-preserve-indentation: t
# End:
