# This file has been generated by node2nix 1.8.0. Do not edit!

{ nodeEnv, fetchurl, fetchgit, globalBuildInputs ? [ ] }:
let
  sources = {
    "@nodelib/fs.scandir-2.1.4" = {
      name = "_at_nodelib_slash_fs.scandir";
      packageName = "@nodelib/fs.scandir";
      version = "2.1.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.scandir/-/fs.scandir-2.1.4.tgz";
        sha512 = "33g3pMJk3bg5nXbL/+CY6I2eJDzZAni49PfJnL5fghPTggPvBd/pFNSgJsdAgWptuFu7qq/ERvOYFlhvsLTCKA==";
      };
    };
    "@nodelib/fs.stat-2.0.4" = {
      name = "_at_nodelib_slash_fs.stat";
      packageName = "@nodelib/fs.stat";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.stat/-/fs.stat-2.0.4.tgz";
        sha512 = "IYlHJA0clt2+Vg7bccq+TzRdJvv19c2INqBSsoOLp1je7xjtr7J26+WXR72MCdvU9q1qTzIWDfhMf+DRvQJK4Q==";
      };
    };
    "@nodelib/fs.walk-1.2.6" = {
      name = "_at_nodelib_slash_fs.walk";
      packageName = "@nodelib/fs.walk";
      version = "1.2.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@nodelib/fs.walk/-/fs.walk-1.2.6.tgz";
        sha512 = "8Broas6vTtW4GIXTAHDoE32hnN2M5ykgCpWGbuXHQ15vEMqr23pB76e/GZcYsZCHALv50ktd24qhEyKr6wBtow==";
      };
    };
    "balanced-match-1.0.2" = {
      name = "balanced-match";
      packageName = "balanced-match";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/balanced-match/-/balanced-match-1.0.2.tgz";
        sha512 = "3oSeUO0TMV67hN1AmbXsK4yaqU7tjiHlbxRDZOpH0KW9+CeX4bRAaX0Anxt0tx2MrpRpWwQaPwIlISEJhYU5Pw==";
      };
    };
    "brace-expansion-1.1.11" = {
      name = "brace-expansion";
      packageName = "brace-expansion";
      version = "1.1.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/brace-expansion/-/brace-expansion-1.1.11.tgz";
        sha512 = "iCuPHDFgrHX7H2vEI/5xpz07zSHB00TpugqhmYtVmMO6518mCuRMoOYFldEBl0g187ufozdaHgWKcYFb61qGiA==";
      };
    };
    "commander-6.2.1" = {
      name = "commander";
      packageName = "commander";
      version = "6.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/commander/-/commander-6.2.1.tgz";
        sha512 = "U7VdrJFnJgo4xjrHpTzu0yrHPGImdsmD95ZlgYSEajAn2JKzDhDTPG9kBTefmObL2w/ngeZnilk+OV9CG3d7UA==";
      };
    };
    "concat-map-0.0.1" = {
      name = "concat-map";
      packageName = "concat-map";
      version = "0.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/concat-map/-/concat-map-0.0.1.tgz";
        sha1 = "d8a96bd77fd68df7793a73036a3ba0d5405d477b";
      };
    };
    "fastq-1.11.0" = {
      name = "fastq";
      packageName = "fastq";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fastq/-/fastq-1.11.0.tgz";
        sha512 = "7Eczs8gIPDrVzT+EksYBcupqMyxSHXXrHOLRRxU2/DicV8789MRBRR8+Hc2uWzUupOs4YS4JzBmBxjjCVBxD/g==";
      };
    };
    "find-up-2.1.0" = {
      name = "find-up";
      packageName = "find-up";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/find-up/-/find-up-2.1.0.tgz";
        sha1 = "45d1b7e506c717ddd482775a2b77920a3c0c57a7";
      };
    };
    "fs.realpath-1.0.0" = {
      name = "fs.realpath";
      packageName = "fs.realpath";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fs.realpath/-/fs.realpath-1.0.0.tgz";
        sha1 = "1504ad2523158caa40db4a2787cb01411994ea4f";
      };
    };
    "glob-7.1.7" = {
      name = "glob";
      packageName = "glob";
      version = "7.1.7";
      src = fetchurl {
        url = "https://registry.npmjs.org/glob/-/glob-7.1.7.tgz";
        sha512 = "OvD9ENzPLbegENnYP5UUfJIirTg4+XwMWGaQfQTY0JenxNvvIKP3U3/tAQSPIu/lHxXYSZmpXlUHeqAIdKzBLQ==";
      };
    };
    "ignore-3.3.10" = {
      name = "ignore";
      packageName = "ignore";
      version = "3.3.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/ignore/-/ignore-3.3.10.tgz";
        sha512 = "Pgs951kaMm5GXP7MOvxERINe3gsaVjUWFm+UZPSq9xYriQAksyhg0csnS0KXSNRD5NmNdapXEpjxG49+AKh/ug==";
      };
    };
    "inflight-1.0.6" = {
      name = "inflight";
      packageName = "inflight";
      version = "1.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/inflight/-/inflight-1.0.6.tgz";
        sha1 = "49bd6331d7d02d0c09bc910a1075ba8165b56df9";
      };
    };
    "inherits-2.0.4" = {
      name = "inherits";
      packageName = "inherits";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/inherits/-/inherits-2.0.4.tgz";
        sha512 = "k/vGaX4/Yla3WzyMCvTQOXYeIHvqOKtnqBduzTHpzpQZzAskKMhZ2K+EnBiSM9zGSoIFeMpXKxa4dYeZIQqewQ==";
      };
    };
    "is-directory-0.3.1" = {
      name = "is-directory";
      packageName = "is-directory";
      version = "0.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-directory/-/is-directory-0.3.1.tgz";
        sha1 = "61339b6f2475fc772fd9c9d83f5c8575dc154ae1";
      };
    };
    "locate-path-2.0.0" = {
      name = "locate-path";
      packageName = "locate-path";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/locate-path/-/locate-path-2.0.0.tgz";
        sha1 = "2b568b265eec944c6d9c0de9c3dbbbca0354cd8e";
      };
    };
    "lodash.intersection-4.4.0" = {
      name = "lodash.intersection";
      packageName = "lodash.intersection";
      version = "4.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.intersection/-/lodash.intersection-4.4.0.tgz";
        sha1 = "0a11ba631d0e95c23c7f2f4cbb9a692ed178e705";
      };
    };
    "lodash.maxby-4.6.0" = {
      name = "lodash.maxby";
      packageName = "lodash.maxby";
      version = "4.6.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.maxby/-/lodash.maxby-4.6.0.tgz";
        sha1 = "082240068f3c7a227aa00a8380e4f38cf0786e3d";
      };
    };
    "lodash.padend-4.6.1" = {
      name = "lodash.padend";
      packageName = "lodash.padend";
      version = "4.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash.padend/-/lodash.padend-4.6.1.tgz";
        sha1 = "53ccba047d06e158d311f45da625f4e49e6f166e";
      };
    };
    "minimatch-3.0.4" = {
      name = "minimatch";
      packageName = "minimatch";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/minimatch/-/minimatch-3.0.4.tgz";
        sha512 = "yJHVQEhyqPLUTgt9B83PXu6W3rx4MvvHvSUvToogpwoGDOUQ+yDrR0HRot+yOCdCO7u4hX3pWft6kWBBcqh0UA==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha1 = "583b1aa775961d4b113ac17d9c50baef9dd76bd1";
      };
    };
    "p-limit-1.3.0" = {
      name = "p-limit";
      packageName = "p-limit";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-limit/-/p-limit-1.3.0.tgz";
        sha512 = "vvcXsLAJ9Dr5rQOPk7toZQZJApBl2K4J6dANSsEuh6QI41JYcsS/qhTGa9ErIUUgK3WNQoJYvylxvjqmiqEA9Q==";
      };
    };
    "p-locate-2.0.0" = {
      name = "p-locate";
      packageName = "p-locate";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-locate/-/p-locate-2.0.0.tgz";
        sha1 = "20a0103b222a70c8fd39cc2e580680f3dde5ec43";
      };
    };
    "p-try-1.0.0" = {
      name = "p-try";
      packageName = "p-try";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/p-try/-/p-try-1.0.0.tgz";
        sha1 = "cbc79cdbaf8fd4228e13f621f2b1a237c1b207b3";
      };
    };
    "path-exists-3.0.0" = {
      name = "path-exists";
      packageName = "path-exists";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-exists/-/path-exists-3.0.0.tgz";
        sha1 = "ce0ebeaa5f78cb18925ea7d810d7b59b010fd515";
      };
    };
    "path-is-absolute-1.0.1" = {
      name = "path-is-absolute";
      packageName = "path-is-absolute";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-is-absolute/-/path-is-absolute-1.0.1.tgz";
        sha1 = "174b9268735534ffbc7ace6bf53a5a9e1b5c5f5f";
      };
    };
    "queue-microtask-1.2.3" = {
      name = "queue-microtask";
      packageName = "queue-microtask";
      version = "1.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/queue-microtask/-/queue-microtask-1.2.3.tgz";
        sha512 = "NuaNSa6flKT5JaSYQzJok04JzTL1CA6aGhv5rfLW3PgqA+M2ChpZQnAC8h8i4ZFkBS8X5RqkDBHA7r4hej3K9A==";
      };
    };
    "reusify-1.0.4" = {
      name = "reusify";
      packageName = "reusify";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/reusify/-/reusify-1.0.4.tgz";
        sha512 = "U9nH88a3fc/ekCF1l0/UP1IosiuIjyTh7hBvXVMHYgVcfGvt897Xguj2UOLDeI5BG2m7/uwyaLVT6fbtCwTyzw==";
      };
    };
    "run-parallel-1.2.0" = {
      name = "run-parallel";
      packageName = "run-parallel";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/run-parallel/-/run-parallel-1.2.0.tgz";
        sha512 = "5l4VyZR86LZ/lDxZTR6jqL8AFE2S0IFLMP26AbjsLVADxHdhB/c0GUsH+y39UfCi3dzz8OlQuPmnaJOMoDHQBA==";
      };
    };
    "true-case-path-1.0.3" = {
      name = "true-case-path";
      packageName = "true-case-path";
      version = "1.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/true-case-path/-/true-case-path-1.0.3.tgz";
        sha512 = "m6s2OdQe5wgpFMC+pAJ+q9djG82O2jcHPOI6RNg1yy9rCYR+WD6Nbpl32fDpfC56nirdRy+opFa/Vk7HYhqaew==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha1 = "b5243d8f3ec1aa35f1364605bc0d1036e30ab69f";
      };
    };
  };
in
{
  codeowners = nodeEnv.buildNodePackage {
    name = "codeowners";
    packageName = "codeowners";
    version = "5.1.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/codeowners/-/codeowners-5.1.0.tgz";
      sha512 = "NKV8qju2JCql0OXH19PD0S1SJuVpy1t7Leio0FMP/hFzkzZYctEVHbJMj3m0aFq7LXs+Hz781A2xt6AUWdrpSA==";
    };
    dependencies = [
      sources."@nodelib/fs.scandir-2.1.4"
      sources."@nodelib/fs.stat-2.0.4"
      sources."@nodelib/fs.walk-1.2.6"
      sources."balanced-match-1.0.2"
      sources."brace-expansion-1.1.11"
      sources."commander-6.2.1"
      sources."concat-map-0.0.1"
      sources."fastq-1.11.0"
      sources."find-up-2.1.0"
      sources."fs.realpath-1.0.0"
      sources."glob-7.1.7"
      sources."ignore-3.3.10"
      sources."inflight-1.0.6"
      sources."inherits-2.0.4"
      sources."is-directory-0.3.1"
      sources."locate-path-2.0.0"
      sources."lodash.intersection-4.4.0"
      sources."lodash.maxby-4.6.0"
      sources."lodash.padend-4.6.1"
      sources."minimatch-3.0.4"
      sources."once-1.4.0"
      sources."p-limit-1.3.0"
      sources."p-locate-2.0.0"
      sources."p-try-1.0.0"
      sources."path-exists-3.0.0"
      sources."path-is-absolute-1.0.1"
      sources."queue-microtask-1.2.3"
      sources."reusify-1.0.4"
      sources."run-parallel-1.2.0"
      sources."true-case-path-1.0.3"
      sources."wrappy-1.0.2"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A tool for working with CODEOWNERS files";
      homepage = "https://github.com/beaugunderson/codeowners#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
