#! /run/current-system/sw/bin/bash
#! nix-shell --pure -i bash -p bash dbus gnused i3status jq

set -eufo pipefail

_spotify_get() {
    dbus-send \
        --dest=org.mpris.MediaPlayer2.spotify \
        --print-reply \
        --session \
        /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get \
        string:'org.mpris.MediaPlayer2.Player' \
        string:"$1"
}

_spotify_xesam_string() {
    sed -n '/string "xesam:'"$1"'"/,/)/p' |
        sed '/string/!d; /xesam/d; s/^.*"\(.*\)".*/\1/'
}

spotify_artist() {
    _spotify_get 'Metadata' | _spotify_xesam_string 'artist'
}

spotify_is_playing() {
    spotify_status | grep -q Playing
}

spotify_status() {
    _spotify_get 'PlaybackStatus' |
        tail -n1 |
        cut -d'"' -f2
}

spotify_title() {
    _spotify_get 'Metadata' | _spotify_xesam_string 'title'
}

i3status | while :; do
    read -r line
    if [[ $line == ",["* ]] && spotify_is_playing; then
        jq -M -c \
            --arg artist "$(spotify_artist)" \
            --arg title "$(spotify_title)" \
            '[{name: "spotify", full_text: "🎧 \($title) - \($artist)"}] + .' \
            <<<"${line#,}" |
            sed 's/^/,/'
    else
        echo "$line"
    fi
done

# Local Variables:
# mode: sh
# sh-shell: "bash"
# End:
